### ISSUE TITLE
Pipeline & data tests

### ISSUE THREAD

**Issue by tavareshugo** [cambiotraining/bacterial-genomics#7]
I have ran through the different steps of the pipelines for the 3 datasets, but only on a subset of 5 samples. 
Here is how long the steps took on our training instance: 

- S_aureus
  - `bacqc` - 6 min
  - `assembleBAC` - 26 min
  - `panaroo` - 5 min
  - `iqtree` - <1 min
- M_tuberculosis
  - `bacqc` - 6 min
  - `bactmap` - 10 min
  - `pseudogenome` - 
  - `mask_pseudogenome` -
  - `iqtree` - 
- S_pneumo
  - `bacqc` - 6 min
  - `assembleBAC` - 23 min
  - `bactmap` - 6 min
  - `pseudogenome` - <1 min
  - `gubbins` - <1min
  - `iqtree` - <1min
  - `funcscan` - 3 min

From these timings, it's clear that running the larger workflows on the full dataset is not doable for a workshop setting, as it would take too long. 
My proposal is that they run the workflows on a subset of 5 samples to see how it looks like, but then they can analyse the outputs from the preprocessed directory. 

For the dowstream steps like phylogeny, it's probably fine to run it on the full datasets, using the preprocessed data as input (might need to tweak the shell scripts in that case, to use the preprocessed directory as input).

**Comment by tavareshugo** [comment]
We will limit most of the steps to 5 samples each. 

We use the preprocessed data for looking at some multiQC reports, microreact, pathogenwatch, etc.

**Comment by bsalehe** [comment]
Hi @avantonder , It is weird that I am experiencing persistent error when running the assembleBAC pipeline and that has halt my progress for nearly an hour now! Below is an error:

<blockquote>
ERROR ~ Error executing process > 'ASSEMBLEBAC:BAKTA (ERX3876908_ERR3864855_T1)'

Caused by:
  Process `ASSEMBLEBAC:BAKTA (ERX3876908_ERR3864855_T1)` terminated with an error exit status (1)


Command executed:

  bakta \
      --skip-plot \
      --threads 8 \
      --prefix ERX3876908_ERR3864855_T1 \
      --db bakta_light_20240119 \
       \
       \
      ERX3876908_ERR3864855_T1_contigs.fa
  cat <<-END_VERSIONS > versions.yml
  "ASSEMBLEBAC:BAKTA":
      bakta: $( echo $(bakta --version 2>&1) | sed 's/^.*bakta //' )
  END_VERSIONS

Command exit status:
  1

Command output:

  parse genome sequences...
  - Checimported: 48
  avantofiltered & revised: 48
  RN: Kicontigs: 48

  start annotation...
  predict tRNAs...
        found: 61
  predict tmRNAs...
        found: 1
  predict rRNAs...
        found: 13
  predict ncRNAs...
        found: 87
  predict ncRNA regions...
        found: 26
  predict CRISPR arrays...
        found: 0
  predict & annotate CDSs...
        predicted: 2524
        discarded spurious: 2
        revised translational exceptions: 0
        detected IPSs: 0
        found PSCCs: 2365
        lookup annotations...
        conduct expert systems...

Command error:

  parse genome sequences...
        imported: 48
        filtered & revised: 48
        contigs: 48

  start annotation...
  predict tRNAs...
        found: 61
  predict tmRNAs...
        found: 1
  predict rRNAs...
        found: 13
  predict ncRNAs...
        found: 87
  predict ncRNA regions...
        found: 26
  predict CRISPR arrays...
        found: 0
  predict & annotate CDSs...
        predicted: 2524
        discarded spurious: 2
        revised translational exceptions: 0
        detected IPSs: 0
        found PSCCs: 2365
        lookup annotations...
        conduct expert systems...
  Traceback (most recent call last):
    File "/usr/local/bin/bakta", line 10, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.10/site-packages/bakta/main.py", line 269, in main
      expert_amr_found = exp_amr.search(cdss, cds_aa_path)
    File "/usr/local/lib/python3.10/site-packages/bakta/expert/amrfinder.py", line 47, in search
      raise Exception(f"amrfinder error! error code: {proc.returncode}. Please, try 'amrfinder_update --force_update --database {amrfinderplus_db_path}' to update AMRFinderPlus's internal database.")
  Exception: amrfinder error! error code: 1. Please, try 'amrfinder_update --force_update --database /home/bajuna/bacterial-genomics/course_files/data/S_aureus/databases/bakta_light_20240119/amrfinderplus-db' to update AMRFinderPlus's internal database.

Work dir:
  /home/bajuna/bacterial-genomics/course_files/data/S_aureus/work/2c/f616fa5ddc9db959ea59eb601c5e8e

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
</blockquote>

I had the same error when I was running the pipeline in the nextflow environment. Then I tried to install nextflow within bakta env, but still the same error comes up. I don't remember if we had this error in the previous iteration of the course. So just asking any idea on this error? Thanks

**Comment by avantonder** [comment]
Hi @bsalehe ,

Did you try:

`amrfinder_update --force_update --database /home/bajuna/bacterial-genomics/course_files/data/S_aureus/databases/bakta_light_20240119/amrfinderplus-db`

We've had a similar issue and I ran that command. I've just tested bakta version 1.9.3 outside of the pipeline and it works. I'm testing the pipeline now with the updated database. If that still doesn't work I'll update the version of bakta and try again.

**Comment by bsalehe** [comment]
Hi @avantonder ,

I have tried to run that command but unfortunately I still get the same error. Maybe you should try updating the pipeline with bakta version 1.9.3 and see if the error will come up or not. Thanks

**Comment by avantonder** [comment]
Hi @bsalehe 

After a bit of trial and error it looks like I've fixed the problem. As far as I can tell it's to do with the version of AMRfinder included with Bakta. The version included with Bakta version 1.9.3 will not update the database properly. However, it appears that the newer version of AMRfinder (3.12), which does the update correctly, is included with Bakta 1.9.4 so I've updated assemblebac to run this version. However, it does mean you'll need to re-download the database and update it with a conda environment containing Bakta version 1.9.4:

`bakta_db download --output . --type light`
`amrfinder_update --force_update --database db-light/amrfinderplus-db/`

Once you've done that, can you try running the pipeline again making sure you delete the version you already have on your system (`rm -rf ~/.nextflow/assets/avantonder/assembleBAC`).

**Comment by tavareshugo** [comment]
this is all working, closing this issue now
